db.movies.update({"title":"The Hobbit:The Desolation of Smaug"},{$set:{"sysnopsis":"A reluctant hobbit, Bilbo Baggins, sets out to the Lonely Mountain with a spirited group of dwarves to reclaim their mountain home - and the gold within it - from the dragon Smaug.""}})









